/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author Hugo
 */
public class CapturaClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form CapturaClientes
     */
    public CapturaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new JScrollPane(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        tblClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        dtchFechaNac = new com.toedter.calendar.JDateChooser();
        txtDomicilio = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbxGenero = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pswdContrasenia = new javax.swing.JPasswordField();
        dtchRegistro = new com.toedter.calendar.JDateChooser();
        lblHora = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Captura Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Altas/Cambios/Bajas de clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);
        tblClientes.setFillsViewportHeight(true);
        tblClientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1150, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombres:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setText("Apellido paterno:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setText("Apellido materno:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setText("Fecha de nacimiento:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel6.setText("Domicilio:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel7.setText("e-mail:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel8.setText("Teléfono:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 160, -1));
        jPanel2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 160, -1));
        jPanel2.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, -1));
        jPanel2.add(dtchFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 170, -1));
        jPanel2.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 170, -1));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 170, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 170, -1));

        jLabel9.setText("RFC:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        jPanel2.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel10.setText("C.U.R.P.:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        jPanel2.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, -1));

        jLabel11.setText("Genero:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jPanel2.add(cmbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, -1));

        jLabel12.setText("Código Postal:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
        jPanel2.add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 170, -1));

        jLabel13.setText("Estado:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel14.setText("Cuidad:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel15.setText("Usuario:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jLabel16.setText("Contraseña:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        jLabel17.setText("Fecha de registro:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel18.setText("Hora de registro:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        txtUsuario.setEditable(false);
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 170, -1));
        jPanel2.add(pswdContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 170, -1));
        jPanel2.add(dtchRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 170, -1));

        lblHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 170, 20));
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 170, -1));
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 930, 290));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 150, 80, -1));

        btnEliminar.setText("Eliminar cliente");
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 230, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbxGenero;
    private com.toedter.calendar.JDateChooser dtchFechaNac;
    private com.toedter.calendar.JDateChooser dtchRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JPasswordField pswdContrasenia;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(javax.swing.JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public javax.swing.JButton getBtnModificar() {
        return btnModificar;
    }

    public void setBtnModificar(javax.swing.JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    public javax.swing.JButton getBtnNuevo() {
        return btnNuevo;
    }

    public void setBtnNuevo(javax.swing.JButton btnNuevo) {
        this.btnNuevo = btnNuevo;
    }

    public javax.swing.JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(javax.swing.JButton btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(javax.swing.JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JTextField getTxtCiudad() {
        return txtCiudad;
    }

    public void setTxtCiudad(JTextField txtCiudad) {
        this.txtCiudad = txtCiudad;
    }

    public JTextField getTxtEstado() {
        return txtEstado;
    }

    public void setTxtEstado(JTextField txtEstado) {
        this.txtEstado = txtEstado;
    }

    public javax.swing.JComboBox getCmbxGenero() {
        return cmbxGenero;
    }

    public void setCmbxGenero(javax.swing.JComboBox cmbxGenero) {
        this.cmbxGenero = cmbxGenero;
    }

    public com.toedter.calendar.JDateChooser getDtchFechaNac() {
        return dtchFechaNac;
    }

    public void setDtchFechaNac(com.toedter.calendar.JDateChooser dtchFechaNac) {
        this.dtchFechaNac = dtchFechaNac;
    }

    public com.toedter.calendar.JDateChooser getDtchRegistro() {
        return dtchRegistro;
    }

    public void setDtchRegistro(com.toedter.calendar.JDateChooser dtchRegistro) {
        this.dtchRegistro = dtchRegistro;
    }

    public javax.swing.JLabel getLblHora() {
        return lblHora;
    }

    public void setLblHora(javax.swing.JLabel lblHora) {
        this.lblHora = lblHora;
    }

    public javax.swing.JPasswordField getPswdContrasenia() {
        return pswdContrasenia;
    }

    public void setPswdContrasenia(javax.swing.JPasswordField pswdContrasenia) {
        this.pswdContrasenia = pswdContrasenia;
    }

    public javax.swing.JTable getTblClientes() {
        return tblClientes;
    }

    public void setTblClientes(javax.swing.JTable tblClientes) {
        this.tblClientes = tblClientes;
    }

    public javax.swing.JTextField getTxtApellidoMaterno() {
        return txtApellidoMaterno;
    }

    public void setTxtApellidoMaterno(javax.swing.JTextField txtApellidoMaterno) {
        this.txtApellidoMaterno = txtApellidoMaterno;
    }

    public javax.swing.JTextField getTxtApellidoPaterno() {
        return txtApellidoPaterno;
    }

    public void setTxtApellidoPaterno(javax.swing.JTextField txtApellidoPaterno) {
        this.txtApellidoPaterno = txtApellidoPaterno;
    }

    public javax.swing.JTextField getTxtCP() {
        return txtCP;
    }

    public void setTxtCP(javax.swing.JTextField txtCP) {
        this.txtCP = txtCP;
    }

    public javax.swing.JTextField getTxtCurp() {
        return txtCurp;
    }

    public void setTxtCurp(javax.swing.JTextField txtCurp) {
        this.txtCurp = txtCurp;
    }

    public javax.swing.JTextField getTxtDomicilio() {
        return txtDomicilio;
    }

    public void setTxtDomicilio(javax.swing.JTextField txtDomicilio) {
        this.txtDomicilio = txtDomicilio;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(javax.swing.JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public javax.swing.JTextField getTxtNombres() {
        return txtNombres;
    }

    public void setTxtNombres(javax.swing.JTextField txtNombres) {
        this.txtNombres = txtNombres;
    }

    public javax.swing.JTextField getTxtRFC() {
        return txtRFC;
    }

    public void setTxtRFC(javax.swing.JTextField txtRFC) {
        this.txtRFC = txtRFC;
    }

    public javax.swing.JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(javax.swing.JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public javax.swing.JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(javax.swing.JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

}