/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author Hugo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCerrar = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniInfoEmpleados = new javax.swing.JMenuItem();
        mniInfoClientes = new javax.swing.JMenuItem();
        mniInfoProductos = new javax.swing.JMenuItem();
        mniInfoVentas = new javax.swing.JMenuItem();
        mniInfoCompras = new javax.swing.JMenuItem();
        mniInfoPedidos = new javax.swing.JMenuItem();
        mniInfoAlmacen = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniABCEmpleados = new javax.swing.JMenuItem();
        mniABCClientes = new javax.swing.JMenuItem();
        mniABCProductos = new javax.swing.JMenuItem();
        mniABCPuesto = new javax.swing.JMenuItem();
        mniABCUsuario = new javax.swing.JMenuItem();
        mniABCMarcas = new javax.swing.JMenuItem();
        mniABCVentas = new javax.swing.JMenuItem();
        mniABCPedidos = new javax.swing.JMenuItem();
        mniAbastecer = new javax.swing.JMenuItem();
        mniABCCategoria = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mniCambiarPass = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Hora:");

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskEscritorioLayout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addGroup(dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        dskEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskEscritorio.setLayer(txtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskEscritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskEscritorio.setLayer(txtFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskEscritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskEscritorio.setLayer(txtHora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Archivo");

        mniCerrar.setText("Cerrar sesión");
        jMenu1.add(mniCerrar);

        mniSalir.setText("Salir");
        jMenu1.add(mniSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informes");

        mniInfoEmpleados.setText("Empleados");
        jMenu2.add(mniInfoEmpleados);

        mniInfoClientes.setText("Clientes");
        jMenu2.add(mniInfoClientes);

        mniInfoProductos.setText("Productos");
        jMenu2.add(mniInfoProductos);

        mniInfoVentas.setText("Ventas");
        jMenu2.add(mniInfoVentas);

        mniInfoCompras.setText("Compras");
        jMenu2.add(mniInfoCompras);

        mniInfoPedidos.setText("Pedidos");
        jMenu2.add(mniInfoPedidos);

        mniInfoAlmacen.setText("Almacén");
        jMenu2.add(mniInfoAlmacen);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Altas/Cambios/Bajas");

        mniABCEmpleados.setText("Empleados");
        jMenu3.add(mniABCEmpleados);

        mniABCClientes.setText("Clientes");
        jMenu3.add(mniABCClientes);

        mniABCProductos.setText("Productos");
        jMenu3.add(mniABCProductos);

        mniABCPuesto.setText("Puesto");
        jMenu3.add(mniABCPuesto);

        mniABCUsuario.setText("Usuario");
        jMenu3.add(mniABCUsuario);

        mniABCMarcas.setText("Marcas");
        jMenu3.add(mniABCMarcas);

        mniABCVentas.setText("Ventas");
        jMenu3.add(mniABCVentas);

        mniABCPedidos.setText("Pedidos");
        jMenu3.add(mniABCPedidos);

        mniAbastecer.setText("Abastecer almacén (Compra)");
        jMenu3.add(mniAbastecer);

        mniABCCategoria.setText("Categoria");
        jMenu3.add(mniABCCategoria);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Más");

        mniCambiarPass.setText("Cambiar contraseña");
        jMenu7.add(mniCambiarPass);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniABCCategoria;
    private javax.swing.JMenuItem mniABCClientes;
    private javax.swing.JMenuItem mniABCEmpleados;
    private javax.swing.JMenuItem mniABCMarcas;
    private javax.swing.JMenuItem mniABCPedidos;
    private javax.swing.JMenuItem mniABCProductos;
    private javax.swing.JMenuItem mniABCPuesto;
    private javax.swing.JMenuItem mniABCUsuario;
    private javax.swing.JMenuItem mniABCVentas;
    private javax.swing.JMenuItem mniAbastecer;
    private javax.swing.JMenuItem mniCambiarPass;
    private javax.swing.JMenuItem mniCerrar;
    private javax.swing.JMenuItem mniInfoAlmacen;
    private javax.swing.JMenuItem mniInfoClientes;
    private javax.swing.JMenuItem mniInfoCompras;
    private javax.swing.JMenuItem mniInfoEmpleados;
    private javax.swing.JMenuItem mniInfoPedidos;
    private javax.swing.JMenuItem mniInfoProductos;
    private javax.swing.JMenuItem mniInfoVentas;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JDesktopPane getDskEscritorio() {
        return dskEscritorio;
    }

    public void setDskEscritorio(javax.swing.JDesktopPane dskEscritorio) {
        this.dskEscritorio = dskEscritorio;
    }

    public javax.swing.JMenuItem getMniABCClientes() {
        return mniABCClientes;
    }

    public void setMniABCClientes(javax.swing.JMenuItem mniABCClientes) {
        this.mniABCClientes = mniABCClientes;
    }

    public javax.swing.JMenuItem getMniABCEmpleados() {
        return mniABCEmpleados;
    }

    public void setMniABCEmpleados(javax.swing.JMenuItem mniABCEmpleados) {
        this.mniABCEmpleados = mniABCEmpleados;
    }

    public javax.swing.JMenuItem getMniABCMarcas() {
        return mniABCMarcas;
    }

    public void setMniABCMarcas(javax.swing.JMenuItem mniABCMarcas) {
        this.mniABCMarcas = mniABCMarcas;
    }

    public javax.swing.JMenuItem getMniABCPedidos() {
        return mniABCPedidos;
    }

    public void setMniABCPedidos(javax.swing.JMenuItem mniABCPedidos) {
        this.mniABCPedidos = mniABCPedidos;
    }

    public javax.swing.JMenuItem getMniABCProductos() {
        return mniABCProductos;
    }

    public void setMniABCProductos(javax.swing.JMenuItem mniABCProductos) {
        this.mniABCProductos = mniABCProductos;
    }

    public javax.swing.JMenuItem getMniABCPuesto() {
        return mniABCPuesto;
    }

    public void setMniABCPuesto(javax.swing.JMenuItem mniABCPuesto) {
        this.mniABCPuesto = mniABCPuesto;
    }

    public javax.swing.JMenuItem getMniABCUsuario() {
        return mniABCUsuario;
    }

    public void setMniABCUsuario(javax.swing.JMenuItem mniABCUsuario) {
        this.mniABCUsuario = mniABCUsuario;
    }

    public javax.swing.JMenuItem getMniABCVentas() {
        return mniABCVentas;
    }

    public void setMniABCVentas(javax.swing.JMenuItem mniABCVentas) {
        this.mniABCVentas = mniABCVentas;
    }

    public javax.swing.JMenuItem getMniAbastecer() {
        return mniAbastecer;
    }

    public void setMniAbastecer(javax.swing.JMenuItem mniAbastecer) {
        this.mniAbastecer = mniAbastecer;
    }

    public javax.swing.JMenuItem getMniCambiarPass() {
        return mniCambiarPass;
    }

    public void setMniCambiarPass(javax.swing.JMenuItem mniCambiarPass) {
        this.mniCambiarPass = mniCambiarPass;
    }

    public javax.swing.JMenuItem getMniCerrar() {
        return mniCerrar;
    }

    public void setMniCerrar(javax.swing.JMenuItem mniCerrar) {
        this.mniCerrar = mniCerrar;
    }

    public javax.swing.JMenuItem getMniInfoClientes() {
        return mniInfoClientes;
    }

    public void setMniInfoClientes(javax.swing.JMenuItem mniInfoClientes) {
        this.mniInfoClientes = mniInfoClientes;
    }

    public javax.swing.JMenuItem getMniInfoEmpleados() {
        return mniInfoEmpleados;
    }

    public void setMniInfoEmpleados(javax.swing.JMenuItem mniInfoEmpleados) {
        this.mniInfoEmpleados = mniInfoEmpleados;
    }

    public javax.swing.JMenuItem getMniInfoPedidos() {
        return mniInfoPedidos;
    }

    public void setMniInfoPedidos(javax.swing.JMenuItem mniInfoPedidos) {
        this.mniInfoPedidos = mniInfoPedidos;
    }

    public javax.swing.JMenuItem getMniInfoProductos() {
        return mniInfoProductos;
    }

    public void setMniInfoProductos(javax.swing.JMenuItem mniInfoProductos) {
        this.mniInfoProductos = mniInfoProductos;
    }

    public javax.swing.JMenuItem getMniInfoVentas() {
        return mniInfoVentas;
    }

    public void setMniInfoVentas(javax.swing.JMenuItem mniInfoVentas) {
        this.mniInfoVentas = mniInfoVentas;
    }

    public javax.swing.JMenuItem getMniSalir() {
        return mniSalir;
    }

    public void setMniSalir(javax.swing.JMenuItem mniSalir) {
        this.mniSalir = mniSalir;
    }

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public void setTxtFecha(JTextField txtFecha) {
        this.txtFecha = txtFecha;
    }

    public JTextField getTxtHora() {
        return txtHora;
    }

    public void setTxtHora(JTextField txtHora) {
        this.txtHora = txtHora;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public javax.swing.JMenuItem getMniInfoCompras() {
        return mniInfoCompras;
    }

    public void setMniInfoCompras(javax.swing.JMenuItem mniInfoCompras) {
        this.mniInfoCompras = mniInfoCompras;
    }

    public javax.swing.JMenuItem getMniABCCategoria() {
        return mniABCCategoria;
    }

    public void setMniABCCategoria(javax.swing.JMenuItem mniABCCategoria) {
        this.mniABCCategoria = mniABCCategoria;
    }

    public JMenuItem getMniInfoAlmacen() {
        return mniInfoAlmacen;
    }

    public void setMniInfoAlmacen(JMenuItem mniInfoAlmacen) {
        this.mniInfoAlmacen = mniInfoAlmacen;
    }
}
